name: Spectrum
main: cooldogedev\Spectrum\Spectrum
description: Spectrum is an implementation of the Spectrum proxy for PocketMine-MP
src-namespace-prefix: cooldogedev\Spectrum
version: 0.0.12a
api: [ 5.0.0 ]
author: cooldogedev
website: https://github.com/cooldogedev/spectrum-pm
load: STARTUP
